"""Deterministic mock VAHAN-shaped registry rows shared by seed + docs.

Every row has is_mock_data=True. Real VAHAN access requires authorised government credentials.
"""

REGISTRY_SOURCE_NOTE = (
    "Mock registry. Real VAHAN access requires authorised government\n"
    "  credentials."
)

# 18 plates from the live snapshot; junk/format-mismatch plates omitted for empty-state demos.
MOCK_REGISTRY: list[dict] = [
    {
        "plate_text": "AP07MN8263",
        "owner_name": "Srinivas Reddy",
        "registration_date": "2019-03-14",
        "registering_authority": "RTO Vijayawada",
        "vehicle_class": "Motor Car",
        "make_model": "Maruti Suzuki Swift",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2027-03-13",
        "insurance_valid_until": "2026-11-20",
        "puc_valid_until": "2026-10-05",
        "is_mock_data": True,
    },
    {
        "plate_text": "AP17K8031",
        "owner_name": "Lakshmi Narayana",
        "registration_date": "2021-07-22",
        "registering_authority": "RTO Guntur",
        "vehicle_class": "Motor Car",
        "make_model": "Hyundai Creta",
        "fuel_type": "Diesel",
        "registration_status": "Active",
        "fitness_valid_until": "2026-07-21",
        "insurance_valid_until": "2027-01-15",
        "puc_valid_until": "2026-09-30",
        "is_mock_data": True,
    },
    {
        "plate_text": "AP31PQ5465",
        "owner_name": "Ananya Krishnan",
        "registration_date": "2020-11-08",
        "registering_authority": "RTO Visakhapatnam",
        "vehicle_class": "Motor Car",
        "make_model": "Tata Nexon",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-11-07",
        "insurance_valid_until": "2026-12-01",
        "puc_valid_until": "2026-08-15",
        "is_mock_data": True,
    },
    {
        "plate_text": "AP32AF2669",
        "owner_name": "Venkatesh Rao",
        "registration_date": "2018-05-30",
        "registering_authority": "RTO Tirupati",
        "vehicle_class": "Motor Car",
        "make_model": "Honda City",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-05-29",
        "insurance_valid_until": "2025-12-10",
        "puc_valid_until": "2026-04-18",
        "is_mock_data": True,
    },
    {
        "plate_text": "AP42MH8766",
        "owner_name": "Pradeep Kumar",
        "registration_date": "2017-09-12",
        "registering_authority": "RTO Kurnool",
        "vehicle_class": "Motor Cycle",
        "make_model": "Honda Activa 6G",
        "fuel_type": "Petrol",
        "registration_status": "Suspended",
        "fitness_valid_until": "2026-09-11",
        "insurance_valid_until": "2026-08-01",
        "puc_valid_until": "2026-07-20",
        "is_mock_data": True,
    },
    {
        "plate_text": "AP40JJ4952",
        "owner_name": "Meenakshi Devi",
        "registration_date": "2016-01-19",
        "registering_authority": "RTO Nellore",
        "vehicle_class": "Motor Car",
        "make_model": "Mahindra XUV300",
        "fuel_type": "Diesel",
        "registration_status": "Expired",
        "fitness_valid_until": "2025-01-18",
        "insurance_valid_until": "2025-06-30",
        "puc_valid_until": "2025-03-12",
        "is_mock_data": True,
    },
    {
        "plate_text": "DL19HR9070",
        "owner_name": "Amit Sharma",
        "registration_date": "2022-02-14",
        "registering_authority": "RTO Delhi South",
        "vehicle_class": "Motor Car",
        "make_model": "Maruti Suzuki Baleno",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2027-02-13",
        "insurance_valid_until": "2027-02-14",
        "puc_valid_until": "2026-11-01",
        "is_mock_data": True,
    },
    {
        "plate_text": "DL42MN2059",
        "owner_name": "Neha Gupta",
        "registration_date": "2019-08-05",
        "registering_authority": "RTO Delhi West",
        "vehicle_class": "Motor Car",
        "make_model": "Kia Seltos",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-08-04",
        "insurance_valid_until": "2026-09-20",
        "puc_valid_until": "2026-10-12",
        "is_mock_data": True,
    },
    {
        "plate_text": "MH17HR3100",
        "owner_name": "Rajesh Patil",
        "registration_date": "2020-04-17",
        "registering_authority": "RTO Pune",
        "vehicle_class": "Motor Car",
        "make_model": "Toyota Innova Crysta",
        "fuel_type": "Diesel",
        "registration_status": "Active",
        "fitness_valid_until": "2026-04-16",
        "insurance_valid_until": "2026-10-31",
        "puc_valid_until": "2026-09-08",
        "is_mock_data": True,
    },
    {
        "plate_text": "MH33BX5218",
        "owner_name": "Sneha Deshmukh",
        "registration_date": "2021-12-01",
        "registering_authority": "RTO Nagpur",
        "vehicle_class": "Motor Cycle",
        "make_model": "TVS Jupiter",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-11-30",
        "insurance_valid_until": "2027-03-01",
        "puc_valid_until": "2026-12-15",
        "is_mock_data": True,
    },
    {
        "plate_text": "MH49MH8182",
        "owner_name": "Imran Sheikh",
        "registration_date": "2018-10-23",
        "registering_authority": "RTO Mumbai Central",
        "vehicle_class": "Motor Car",
        "make_model": "Maruti Suzuki Dzire",
        "fuel_type": "CNG",
        "registration_status": "Active",
        "fitness_valid_until": "2025-10-22",
        "insurance_valid_until": "2026-06-15",
        "puc_valid_until": "2026-05-01",
        "is_mock_data": True,
    },
    {
        "plate_text": "RJ03PQ9713",
        "owner_name": "Vikram Singh Rathore",
        "registration_date": "2019-06-11",
        "registering_authority": "RTO Jaipur",
        "vehicle_class": "Motor Car",
        "make_model": "Mahindra Scorpio",
        "fuel_type": "Diesel",
        "registration_status": "Active",
        "fitness_valid_until": "2026-06-10",
        "insurance_valid_until": "2026-12-20",
        "puc_valid_until": "2026-08-30",
        "is_mock_data": True,
    },
    {
        "plate_text": "RJ28MN7912",
        "owner_name": "Pooja Agarwal",
        "registration_date": "2022-09-28",
        "registering_authority": "RTO Udaipur",
        "vehicle_class": "Motor Car",
        "make_model": "Hyundai i20",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2027-09-27",
        "insurance_valid_until": "2027-09-28",
        "puc_valid_until": "2027-01-10",
        "is_mock_data": True,
    },
    {
        "plate_text": "RJ44JJ9823",
        "owner_name": "Harish Chandra",
        "registration_date": "2015-03-07",
        "registering_authority": "RTO Jodhpur",
        "vehicle_class": "Motor Car",
        "make_model": "Tata Tiago",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-03-06",
        "insurance_valid_until": "2026-07-22",
        "puc_valid_until": "2026-06-01",
        "is_mock_data": True,
    },
    {
        "plate_text": "TN37AB3123",
        "owner_name": "Karthik Subramanian",
        "registration_date": "2020-01-25",
        "registering_authority": "RTO Coimbatore",
        "vehicle_class": "Motor Car",
        "make_model": "Renault Kwid",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-01-24",
        "insurance_valid_until": "2026-11-05",
        "puc_valid_until": "2026-09-18",
        "is_mock_data": True,
    },
    {
        "plate_text": "TS03AF3704",
        "owner_name": "Fatima Begum",
        "registration_date": "2021-05-16",
        "registering_authority": "RTO Hyderabad Central",
        "vehicle_class": "Motor Car",
        "make_model": "Maruti Suzuki Ertiga",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-05-15",
        "insurance_valid_until": "2027-05-16",
        "puc_valid_until": "2026-10-22",
        "is_mock_data": True,
    },
    {
        "plate_text": "TS42AF3700",
        "owner_name": "Ravi Teja",
        "registration_date": "2017-11-03",
        "registering_authority": "RTO Warangal",
        "vehicle_class": "Motor Cycle",
        "make_model": "Bajaj Pulsar 150",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2026-11-02",
        "insurance_valid_until": "2026-08-10",
        "puc_valid_until": "2026-07-01",
        "is_mock_data": True,
    },
    {
        "plate_text": "TS48AB8163",
        "owner_name": "Divya Reddy",
        "registration_date": "2023-01-09",
        "registering_authority": "RTO Rangareddy",
        "vehicle_class": "Motor Car",
        "make_model": "MG Hector",
        "fuel_type": "Petrol",
        "registration_status": "Active",
        "fitness_valid_until": "2028-01-08",
        "insurance_valid_until": "2027-01-09",
        "puc_valid_until": "2026-12-01",
        "is_mock_data": True,
    },
]
